### ISSUE TITLE
Crashed on sticker prediction on mobile

### ISSUE THREAD

**Issue by hooddy** [UnigramDev/Unigram#1265]
Latest 3.13.2635 build is crashed while predict sticker on message compose on mobile.

**Comment by FrayxRulez** [comment]
Might depend on specific stickers actually, or specific emoji

**Comment by hooddy** [comment]
Seem it fixed in todays release. (yes it was no on all smiles).

**Comment by FrayxRulez** [comment]
Nothing has changed in today release about stickers (I literally changed a single character) so this is probably not fixed 😁

**Comment by hooddy** [comment]
Yeah it still occurred from different smileys and stickers... (((

**Comment by Tourniquet88** [comment]
This crash makes Unigram basically unusable to me. Everytime I just want to insert an Emoji, Unigram crashes will wanting to show a corresponding sticker. While loading the Sticker preview, it just crashes. I just see the "sticker popup" for a split second and then the App crashes.

**Comment by FrayxRulez** [comment]
This "should" be fixed in 3.13.2638 that's currently in certification phase
