### ISSUE TITLE
Backgrounds can't be blurred anymore (v3.14)

### ISSUE THREAD

**Issue by strollingHeifer** [UnigramDev/Unigram#1318]
My background used to be blurred, but after the update to Unigram v3.14, that effect is now gone. The option seems gone from the settings menu as well. I can only select new wallpapers, but can't make a decision whether I would like it to be blurred or not.

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/eac766b7dbeb19e5824da010fbdb7ac21aff6dea

**Comment by strollingHeifer** [comment]
The option to blurr wallpapers is there for me now in v3.14.2665. However, when selecting the option to blurr them, Unigram still won't do it.

**Comment by strollingHeifer** [comment]
Turns out, restarting Unigram does the trick. The wallpapers will be blurred after a restart.
It's still not working as intended, because a restart should not be necessary for the setting to go into effect. But maybe my observation helps to track down the bug.
