### ISSUE TITLE
add announcement of online status/ last seen time in contact/chat list for screen readers

### ISSUE THREAD

**Issue by alipanjei** [UnigramDev/Unigram#1353]
hi
pleas add announcement of online status/ last seen time in contact/chat list for screen readers. It was available around last year, and got removed for some reason.
in official telegram apps for other platforms such as android, online status and last seen time is announced with screen readers, in both places mentioned above
in unigram however, it's not present.

**Comment by MarcAnt01** [comment]
#1343 should be needed first for this, otherwise the status of admins won’t be announced

**Comment by sukiletxe** [comment]
I believe this is fixed. Contact list and group members work. In contact lists, arrowing tells me if the person is online or when his/her last seen time was, and in group members too. I don't know if anything is missing.

**Comment by alipanjei** [comment]
It's still missing from chat list, where One can see all groups, channels and users; When I read that list with telegram for android, it announces last seen time for users. Here It doesn't

**Comment by sukiletxe** [comment]
Ah, yes, there it's not announced. In iOS it's not announced either, that's why I found it strange. If the list item includes the current information too (i. e., sender, unread messages, last message, and date) I wouldn't mind if it got added. I personally don't find it really useful, but as I said I come from iOS where no messaging app except Facebook Messenger does this.
