### ISSUE TITLE
Inking and cropping functions don't work as expected

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1534]
- Inked pictures are sent without ink;
- Cropped pictures can't be sent

**Comment by cewbdex** [comment]
True, works for avatars, tho.

**Comment by MarcAnt01** [comment]
I don't understand what you mean

**Comment by cewbdex** [comment]
@MarcAnt01 you can ink and crop avatar image you are setting and it works.

**Comment by MarcAnt01** [comment]
Ah, didn't know there was such possibility now lol

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/077cb7a402d70bd3eff05209110dceba15044b9a

**Comment by revanmj** [comment]
Was the fix included in beta already? Because with 4.0.4932 I still cannot send cropped pictures (I get error message with a stacktrace).

**Comment by FrayxRulez** [comment]
> Was the fix included in beta already? Because with 4.0.4932 I still cannot send cropped pictures (I get error message with a stacktrace).

You might want to provide more details then

**Comment by revanmj** [comment]
Sure - repro steps:
1. Make a screenshot with Print Screen key
2. Paste it to private conversation
3. Use crop tool (without using crop tool it can be sent successfully)
4. Try to send it - below stacktrace shows up (unfortunately I cannot copy text from it)

![unigram03](https://user-images.githubusercontent.com/1777618/83267097-05220900-a1c4-11ea-9d15-d201f1dd0a6c.png)

**Comment by MarcAnt01** [comment]
Cannot reproduce

**Comment by revanmj** [comment]
Confirm cropping works without crashing on latest beta. This also fixed cropping different area of the image than the one selected, thanks!
