### ISSUE TITLE
Hide is typing etc. from recent actions

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1885]

**Comment by FrayxRulez** [comment]
Done

**Comment by MarcAnt01** [comment]
I see that it's still present somehow
![image](https://user-images.githubusercontent.com/43090263/102009691-73ca4c80-3d39-11eb-89bf-1e272131d5d8.png)

**Comment by MarcAnt01** [comment]
Maybe related to the updated status animation fixes Idk

**Comment by MarcAnt01** [comment]
@MarcAnt01
