### ISSUE TITLE
Chat view remains cut when using touch keyboard and minimizing the window

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#2342]
Minimizing the window with software keyboard on and then maximizing it keeps the chat view cut.

![image](https://user-images.githubusercontent.com/9021297/115953171-1bc30400-a4ea-11eb-9714-7a6af261c401.png)
![image](https://user-images.githubusercontent.com/9021297/115953162-0b128e00-a4ea-11eb-8a76-93577fae9992.png)

**Comment by FrayxRulez** [comment]
Fixed at some point

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/188328741-8a1c5674-8dd1-477c-8c44-3c7de611eba4.png)
I can still reproduce it, but it doesn't seem to happen every time like it used to

**Comment by FrayxRulez** [comment]
The screenshot shows a system bug to me

**Comment by MarcAnt01** [comment]
> The screenshot shows a system bug to me

Idk, it looks like exactly the same issue which you believed to be fixed

**Comment by FrayxRulez** [comment]
> Idk, it looks like exactly the same issue which you believed to be fixed. With the difference is that after the removal of the custom keyboard implementation it scrolls up

It doesn't, because it clearly show the whole app content being moved by Windows--what I fixed (or better, removed) was the custom handling of the keyboard visibility, that as shown by @cewbdex only affected the chat input area position.
