### ISSUE TITLE
The color of the UI interface is displayed incorrectly when switching between Windows themes in a particular situation

### ISSUE THREAD

**Issue by MiaoLuoNa** [UnigramDev/Unigram#2774]
I haven't figured out how to reproduce the issue 100% consistently, as it appears to be a wrong color display for random UI layouts, all I know is that switching Windows themes under certain conditions will make it, and restarting unigram will fix it
![image](https://user-images.githubusercontent.com/62191675/175815711-3b1a2b96-0085-4af2-b7ea-d5f3fdcc4275.png)
↓after restart
![image](https://user-images.githubusercontent.com/62191675/175815714-666076c5-a360-4c99-9eaa-509f13b5a16d.png)
![image](https://user-images.githubusercontent.com/62191675/175815721-8b8e43fd-745a-4ff4-9760-2443247db002.png)
![image](https://user-images.githubusercontent.com/62191675/175815722-8fce7711-1d78-4604-9519-9fe7e7b35064.png)
![image](https://user-images.githubusercontent.com/62191675/175815725-862c56c6-beb6-44f4-9175-bd2a4d4e05f1.png)
↑the search bar
![image](https://user-images.githubusercontent.com/62191675/175815728-c9547c74-0b75-4bc5-9449-7c9f83a6d479.png)

unigram 8.8 7433

**Comment by FrayxRulez** [comment]
Some issues related to themes should be fixed in 8.9, can you confirm?

**Comment by FrayxRulez** [comment]
@FrayxRulez Can three people react to this message?

**Comment by miaoluona** [comment]
![image](https://user-images.githubusercontent.com/62191675/183288757-1a8de9de-be44-49ea-9f0e-11c7df650e08.png)
I don't think so....As you see, my version is 8.9 but issues are still there

**Comment by FrayxRulez** [comment]
What's your Windows version?

**Comment by miaoluona** [comment]
![image](https://user-images.githubusercontent.com/62191675/183288945-26b82d37-31ac-4370-80b1-655528a18836.png)
Windows 11 Pro for Workstations 22H2 22622.436

**Comment by FrayxRulez** [comment]
How do you switch between themes?

**Comment by MiaoLuoNa** [comment]
1.Create themes with light mode and dark mode and choose one.(Windows settings)
2.Open Unigram.
3.Switch to another theme.

Interface in Chinese 
![](https://user-images.githubusercontent.com/62191675/183293379-02105206-b816-4d5e-911c-c99bb02ba5b7.png)

**Comment by MiaoLuoNa** [comment]
Actually I'm using a kind of software to automatically change the theme when the sky is dark. So it will change the theme very often. But whether manual or automatic. This issue is still there.

**Comment by FrayxRulez** [comment]
@MiaoLuoNa What if you use the built-in feature to change app theme when it’s dark?

**Comment by MiaoLuoNa** [comment]
What do you mean? unigram feature or windows feature(switch mode but not by theme)

**Comment by MiaoLuoNa** [comment]
More specific description plz

**Comment by FrayxRulez** [comment]
@MiaoLuoNa So I think I was able to reproduce the issue. This seems to happen if the system theme changes while Unigram is minimized (and consequently suspended)

**Comment by MiaoLuoNa** [comment]
May I have your TG number? It's not convenient to upload video here

**Comment by makisukurisu** [comment]
@MiaoLuoNa Join Unigram Insiders:

https://t.me/unigraminsiders

**Comment by FrayxRulez** [comment]
I believe that the issue was fixed in version 8.9.7527, can you give it a shot? My Telegram username is the same as here.

**Comment by makisukurisu** [comment]
Looks like it is, to me. If it's not - please, feel free to reopen this issue.
