### ISSUE TITLE
Media sent with timer is not self-destructing

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#2846]
**Describe the bug**
When receiving self-destruct timed photos or videos, the media does not self-destruct. They are displayed on the screen infinitely.

**To Reproduce**
1. In a chat, receive a photo or video with self-destruct timer
2. Open the media
3. The media won't disappear

**Expected behavior**
Media must be destroyed at the end of the specified time.

**Screenshots**
Cannot capture screen with self-destructing media. In the case of videos, not even the blur is applied in the media preview.

**Version Info**
 - Unigram: [9.0 7771 x64]
 - Windows: [10 21H2]

**Additional context**
When opening the media, it cannot be opened again. But as long as it's open, I can watch and play for as long as I want.

**Comment by luccascomvoce** [comment]
![Screenshot_2022-09-26-16-01-27-060_org telegram messenger web](https://user-images.githubusercontent.com/65538684/192361105-635d85d3-6b4e-456f-b900-aeaf8a5ad1db.jpg)

Video with self-destruct timer has no blur.

**Comment by MarcAnt01** [comment]
I think this is related to the gallery redesign

**Comment by FrayxRulez** [comment]
Fixed in 6eaf37b3a8bb969a0707272790abe56adf80ae64

**Comment by luccascomvoce** [comment]
The problem came back, but now it's different
https://github.com/UnigramDev/Unigram/issues/3019
