### ISSUE TITLE
Links are missing thumbnails and cannot be opened from the Shared Media page

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#296]

**Comment by Fernandus91** [comment]
Also, Shared Media page shows two photos icons, the first is empty. 
![wp_ss_20170619_0001](https://user-images.githubusercontent.com/29466231/27302385-32f03cee-5537-11e7-802e-0df6121e24a3.png)
Other categories too shows at least two months of media that you can't open.

**Comment by larsschellhas** [comment]
This is not related to this issue. Please open another issue for it ;) @Fernandus91

**Comment by Fernandus91** [comment]
Ok, thanks. I thought this thread could embrace all Shared Media page bugs :)

**Comment by larsschellhas** [comment]
Thanks :) it's better to use multiple issues, because then you can track every single of them and close them as soon as they are solved

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/83b7ba1424802ad06f75950b12e0d04bc41b80b7

**Comment by larsschellhas** [comment]
@FrayxRulez I have to admit that I put two issues into one, but in you GIF the links still do not have a thumbnail :'D so is it really fixed/implemented? 😨

**Comment by FrayxRulez** [comment]
Not every link has a thumbnail
