### ISSUE TITLE
False Directionality for RTL Languages

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#878]
Currently the RTL messages/instant views are falsely aligned to left.

Version: 2.3.1977

**Comment by FrayxRulez** [comment]
Sadly, at the moment, Windows doesn’t provide any API to detect text directionality and text elements don’t adapt autonomously depending on their content. There’s no way for me to solve this issue.

**Comment by raminmjj** [comment]
please check this link:
https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/design-for-bidi-text
I hope this may help you @FrayxRulez.

**Comment by FrayxRulez** [comment]
It doesn’t help as there isn’t any API reference, is just a textual explanation about the fact that RTL languages should be right aligned.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/94e5d3e87338ad2efa9710dbff4dca979232d9d8

**Comment by Xashyar** [comment]
> 
> 
> Fixed in [94e5d3e](https://github.com/UnigramDev/Unigram/commit/94e5d3e87338ad2efa9710dbff4dca979232d9d8)

the problem still persists in Conversation Tooltips:
![image](https://user-images.githubusercontent.com/34171942/48297957-938f4680-e4c9-11e8-9124-7f50c0cda6f4.png)

**Comment by FrayxRulez** [comment]
Would be useful if you can write a full list of places where this problem occurs, so I can fix them all at once.
